/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendaftaran;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Scanner;
import java.awt.*;


/**
 *
 * @author SANJAYA
 */
public class FormDaftarTera extends javax.swing.JFrame {
    DefaultTableModel tabModel;
    ResultSet RsDaftar=null;

    /**
     * Creates new form daftar tera
     */
    public FormDaftarTera() {
        initComponents();
        tampilData();
        
        Dimension screenSize=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize=this.getSize();
        if(frameSize.height > screenSize.height){
        frameSize.height=screenSize.height;
        }
        if(frameSize.width > screenSize.width){
        frameSize.width=screenSize.width;
        }
        this.setLocation((screenSize.width - frameSize.width) / 2,
        (screenSize.height = screenSize.height) / 20); 
        

    }
    //fungsi untuk menampilkan data pendaftaran ke dalam tabel
    private void tampilData(){
        try{
            Object[] judul_kolom = {"No Order","Pemilik UTTP", "Jenis UTTP", "Merk/Tipe", "No Seri", "Kapasitas", "Daya Baca", "Penerima", "Tanggal Order"};
            tabModel=new DefaultTableModel(null,judul_kolom);
            TabelPendaftaran.setModel(tabModel);
            
            Connection conn=(Connection)koneksi.koneksiDB();
            Statement stt=conn.createStatement();
            tabModel.getDataVector().removeAllElements();
            
            RsDaftar=stt.executeQuery("SELECT * from kartu_order ");  
            while(RsDaftar.next()){
                Object[] data={
                    RsDaftar.getString("No_Order"),
                    RsDaftar.getString("Pemilik_UTTP"),
                    RsDaftar.getString("Jenis_UTTP"),
                    RsDaftar.getString("Merk_Tipe"),
                    RsDaftar.getString("No_Seri"),
                    RsDaftar.getString("Kapasitas"),
                    RsDaftar.getString("Daya_Baca"),
                    RsDaftar.getString("Penerima"),
                    RsDaftar.getString("CreateDate")         
                };
               tabModel.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
  
    }
   
    //menampilkan data ke form saat data pada tabel di klik 
   void tblKeForm(){
        tes.setText(tabModel.getValueAt(TabelPendaftaran.getSelectedRow(),0)+"");
        jTextPemilik_UTTP.setText(tabModel.getValueAt(TabelPendaftaran.getSelectedRow(),1)+"");
        jTextMerkTipe.setText(tabModel.getValueAt(TabelPendaftaran.getSelectedRow(),3)+"");
        jComboBoxJenisUTTP.setSelectedItem(tabModel.getValueAt(TabelPendaftaran.getSelectedRow(),2)+"");
        jTextNoSeri.setText(tabModel.getValueAt(TabelPendaftaran.getSelectedRow(),4)+"");
        jTextKapasitas.setText(tabModel.getValueAt(TabelPendaftaran.getSelectedRow(),5)+"");
        jTextDayaBaca.setText(tabModel.getValueAt(TabelPendaftaran.getSelectedRow(),6)+"");
        jComboBoxPenerima.setSelectedItem(tabModel.getValueAt(TabelPendaftaran.getSelectedRow(),7)+"");
        
        jButtonUpdate.setEnabled(true);
        jButtonDelete.setEnabled(true);
        jButtonCancel.setEnabled(true);
        jButtonSave.setEnabled(false);
    }
   
   //membersihkan form
   private void BersihData(){
        jTextPemilik_UTTP.setText("");
        jTextMerkTipe.setText("");
        jComboBoxJenisUTTP.setSelectedIndex(0);
        jTextNoSeri.setText(""); 
        jTextKapasitas.setText("");
        jTextDayaBaca.setText("");
        jComboBoxPenerima.setSelectedIndex(0);
        tes.setText("");
    } 
   
   private void seteditOn(){
        jTextPemilik_UTTP.setEnabled(true);
        jTextMerkTipe.setEnabled(true);
        jComboBoxJenisUTTP.setEnabled(true);
        jTextNoSeri.setEnabled(true);
        jTextKapasitas.setEnabled(true);
        jTextDayaBaca.setEnabled(true);
        jComboBoxPenerima.setEnabled(true);
        tes.setEnabled(true);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHeader = new javax.swing.JLabel();
        jLabelPemilikUTTP = new javax.swing.JLabel();
        jTextPemilik_UTTP = new javax.swing.JTextField();
        jLabelJenisUTTP = new javax.swing.JLabel();
        jTextMerkTipe = new javax.swing.JTextField();
        jLabelPenerima = new javax.swing.JLabel();
        jComboBoxJenisUTTP = new javax.swing.JComboBox();
        jLabelMerkTipe = new javax.swing.JLabel();
        jTextNoSeri = new javax.swing.JTextField();
        jLabelNoSeri = new javax.swing.JLabel();
        jTextKapasitas = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelPendaftaran = new javax.swing.JTable();
        jLabelKapasitas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelDayaBaca = new javax.swing.JLabel();
        jTextDayaBaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxPenerima = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextCari = new javax.swing.JTextField();
        tes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelHeader.setBackground(new java.awt.Color(0, 0, 51));
        jLabelHeader.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelHeader.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHeader.setText("DATA PENDAFTARAN TERA");
        jLabelHeader.setOpaque(true);

        jLabelPemilikUTTP.setText("Pemilik UTTP");

        jTextPemilik_UTTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPemilik_UTTPActionPerformed(evt);
            }
        });

        jLabelJenisUTTP.setText("Jenis UTTP");

        jLabelPenerima.setText("Penerima");

        jComboBoxJenisUTTP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Jenis UTTP", "CB", "Elektronik", "Emas" }));

        jLabelMerkTipe.setText("Merk/Tipe");

        jTextNoSeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNoSeriActionPerformed(evt);
            }
        });

        jLabelNoSeri.setText("No Seri");

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        TabelPendaftaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelPendaftaran.setCellSelectionEnabled(true);
        TabelPendaftaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelPendaftaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelPendaftaran);
        TabelPendaftaran.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabelKapasitas.setText("Kapasitas");

        jLabel2.setText("jLabel2");

        jLabelDayaBaca.setText("Daya Baca");

        jLabel4.setText("Developed by Sanjaya");

        jLabel5.setText("Beta v1.0");

        jComboBoxPenerima.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Nama Pegawai", "Mila Rahmawati", "Pe'i", "Sanjaya" }));

        jLabel1.setText("Cari");

        jTextCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextCariKeyReleased(evt);
            }
        });

        tes.setEditable(false);
        tes.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabelMerkTipe)
                            .addComponent(jLabelNoSeri)
                            .addComponent(jLabelPemilikUTTP)
                            .addComponent(jLabelJenisUTTP)
                            .addComponent(jLabelPenerima)
                            .addComponent(jLabelDayaBaca)
                            .addComponent(jLabelKapasitas))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxJenisUTTP, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextPemilik_UTTP, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextDayaBaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMerkTipe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNoSeri, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextKapasitas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(30, 30, 30)
                                .addComponent(jTextCari, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(374, 374, 374)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel)
                        .addGap(355, 355, 355)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(tes, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextPemilik_UTTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(jLabelPemilikUTTP))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxJenisUTTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelJenisUTTP))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextMerkTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMerkTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextNoSeri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNoSeri))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelKapasitas))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextDayaBaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDayaBaca))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPenerima)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonCancel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //menangani proses saat button save di klik
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        String Pemilik_UTTP=jTextPemilik_UTTP.getText();
        String Jenis_UTTP=jComboBoxJenisUTTP.getSelectedItem().toString();
        String Merk_Tipe=jTextMerkTipe.getText();
        String No_Seri=jTextNoSeri.getText();
        String Kapasitas=jTextKapasitas.getText();
        String Daya_Baca=jTextDayaBaca.getText();
        String Penerima=jComboBoxPenerima.getSelectedItem().toString();

        java.util.Date tanggal = new java.util.Date();
        java.text.SimpleDateFormat TanggalFormat= new java.text.SimpleDateFormat("yyyy-MM-dd");
        String CreateDate=TanggalFormat.format(tanggal);

        if (Pemilik_UTTP.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"Pemilik UTTP tidak boleh kosong");
        }else if (Jenis_UTTP.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Jenis UTTP tidak boleh kosong");
        }else if (Merk_Tipe.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Merk/Tipe tidak boleh kosong");
        }else if (No_Seri.isEmpty()) {
            JOptionPane.showMessageDialog(null,"No Seri tidak boleh kosong");
        }else if (Kapasitas.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Kapasitas tidak boleh kosong");
        }else if (Daya_Baca.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Daya Baca tidak boleh kosong");
        }else if (Penerima.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Penerima tidak boleh kosong");
        }else{
            try{
                Connection conn=(Connection)koneksi.koneksiDB();
                Statement stt=conn.createStatement();
                stt.executeUpdate("insert into kartu_order (Pemilik_UTTP,Jenis_UTTP,Merk_Tipe,No_Seri,Kapasitas,Daya_Baca,Penerima,CreateDate)"+
                    "VALUES('"+Pemilik_UTTP+"','"+Jenis_UTTP+"','"+Merk_Tipe+"','"+No_Seri+"','"+Kapasitas+"','"+Daya_Baca+"','"+Penerima+"','"+CreateDate+"')");
                BersihData();
                tampilData();
                JOptionPane.showMessageDialog(this,"Data berhasil disimpan","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Simpan data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButtonSaveActionPerformed

    //menangani proses saat button Update di klik
    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        String No_Order=tes.getText();
        String Pemilik_UTTP=jTextPemilik_UTTP.getText();
        String Jenis_UTTP=jComboBoxJenisUTTP.getSelectedItem().toString();
        String Merk_Tipe=jTextMerkTipe.getText();
        String No_Seri=jTextNoSeri.getText();
        String Kapasitas=jTextKapasitas.getText();
        String Daya_Baca=jTextDayaBaca.getText();
        String Penerima=jComboBoxPenerima.getSelectedItem().toString();

        java.util.Date tanggal = new java.util.Date();
        java.text.SimpleDateFormat TanggalFormat= new java.text.SimpleDateFormat("dd-MM-yyyy");
        String CreateDate=TanggalFormat.format(tanggal);

        if (Pemilik_UTTP.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"Pemilik UTTP tidak boleh kosong");
        }else if (Jenis_UTTP.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Jenis UTTP tidak boleh kosong");
        }else if (Merk_Tipe.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Merk/Tipe tidak boleh kosong");
        }else if (No_Seri.isEmpty()) {
            JOptionPane.showMessageDialog(null,"No Seri tidak boleh kosong");
        }else if (Kapasitas.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Kapasitas tidak boleh kosong");
        }else if (Daya_Baca.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Daya Baca tidak boleh kosong");
        }else if (Penerima.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Daya Baca tidak boleh kosong");
        }
        else{
            try{
                Connection conn=(Connection)koneksi.koneksiDB();
                Statement stt=conn.createStatement();
                stt.executeUpdate("UPDATE kartu_order SET Pemilik_UTTP='"+Pemilik_UTTP+"', Jenis_UTTP='"+Jenis_UTTP+"', Merk_Tipe='"+Merk_Tipe+"', No_Seri='"+No_Seri+"',"+
                    "Kapasitas='"+Kapasitas+"', Daya_Baca='"+Daya_Baca+"', Penerima='"+Penerima+"' WHERE No_Order='"+No_Order+"'");
                BersihData();
                tampilData();
                JOptionPane.showMessageDialog(this,"Data berhasil diubah","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Ubah data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButtonUpdateActionPerformed

    //menangani proses saat button delete di klik
    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        String Pemilik_UTTP=jTextPemilik_UTTP.getText();

        if (Pemilik_UTTP.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"Pemilik UTTP tidak boleh kosong");
            jTextPemilik_UTTP.requestFocus();
        }else if(JOptionPane.showConfirmDialog(null,"Apakah anda yakin akan menghapus data ini?",
            "Informasi",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE)==JOptionPane.OK_OPTION){
        try{
            Connection conn=(Connection)koneksi.koneksiDB();
            Statement stt=conn.createStatement();
            stt.executeUpdate("DELETE FROM kartu_order WHERE Pemilik_UTTP='"+Pemilik_UTTP+"'");
            BersihData();
            tampilData();
            JOptionPane.showMessageDialog(this,"Data berhasil di hapus","Success",JOptionPane.INFORMATION_MESSAGE);
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this,"Delete data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    //menangani proses saat button cancel di klik
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        BersihData();
        jButtonSave.setEnabled(true);
        jButtonUpdate.setEnabled(false);
        jButtonDelete.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    // pencarian data
    private void cariData(String key){
        try{
            Object[] judul_kolom = {"No Order","Pemilik UTTP", "Jenis UTTP", "Merk/Tipe", "No Seri", "Kapasitas", "Daya Baca", "Penerima", "Tanggal Order"};
            tabModel=new DefaultTableModel(null,judul_kolom);
            TabelPendaftaran.setModel(tabModel);
            
            Connection conn=(Connection)koneksi.koneksiDB();
            Statement stt=conn.createStatement();
            tabModel.getDataVector().removeAllElements();
            
            RsDaftar=stt.executeQuery("SELECT * from kartu_order WHERE No_Order LIKE '%"+key+"%' OR Pemilik_UTTP LIKE '%"+key+"%' OR Jenis_UTTP LIKE '%"+key+"%' OR Merk_Tipe LIKE '%"+key+"%'OR No_Seri LIKE '%"+key+"%'OR Kapasitas LIKE '%"+key+"%' OR Daya_Baca LIKE '%"+key+"%' OR Penerima LIKE '%"+key+"%' OR CreateDate LIKE '%"+key+"%'");  
            while(RsDaftar.next()){
                Object[] data={
                    RsDaftar.getString("No_Order"),
                    RsDaftar.getString("Pemilik_UTTP"),
                    RsDaftar.getString("Jenis_UTTP"),
                    RsDaftar.getString("Merk_Tipe"),
                    RsDaftar.getString("No_Seri"),
                    RsDaftar.getString("Kapasitas"),
                    RsDaftar.getString("Daya_Baca"),
                    RsDaftar.getString("Penerima"),
                    RsDaftar.getString("CreateDate")       
                };
               tabModel.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }
    
    //menangani proses saat tabel pendaftaran di klik
    private void TabelPendaftaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelPendaftaranMouseClicked
        // TODO add your handling code here:
        seteditOn();
        tblKeForm();
    }//GEN-LAST:event_TabelPendaftaranMouseClicked

    private void jTextPemilik_UTTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPemilik_UTTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPemilik_UTTPActionPerformed

    private void jTextNoSeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNoSeriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNoSeriActionPerformed

    private void jTextCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCariKeyReleased
        // TODO add your handling code here:
         String key=jTextCari.getText();
        System.out.println(key);  
        
        if(key!=""){
            cariData(key);
        }else{
            tampilData();
        }
    }//GEN-LAST:event_jTextCariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDaftarTera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDaftarTera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDaftarTera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDaftarTera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDaftarTera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelPendaftaran;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox jComboBoxJenisUTTP;
    private javax.swing.JComboBox<String> jComboBoxPenerima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDayaBaca;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelJenisUTTP;
    private javax.swing.JLabel jLabelKapasitas;
    private javax.swing.JLabel jLabelMerkTipe;
    private javax.swing.JLabel jLabelNoSeri;
    private javax.swing.JLabel jLabelPemilikUTTP;
    private javax.swing.JLabel jLabelPenerima;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextCari;
    private javax.swing.JTextField jTextDayaBaca;
    private javax.swing.JTextField jTextKapasitas;
    private javax.swing.JTextField jTextMerkTipe;
    private javax.swing.JTextField jTextNoSeri;
    private javax.swing.JTextField jTextPemilik_UTTP;
    private javax.swing.JTextField tes;
    // End of variables declaration//GEN-END:variables
}
